development:
  adapter: mysql2
  encoding: utf8
  database: equine_office_dev
  username: root
  password: JeffBurroughsMay061983%&


production:
  adapter: mysql2
  encoding: utf8
  database: equine_office_dev
  username: root
  password: JeffBurroughsMay061983%&
