# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60c262ffcdd06c82992cde820c1e0e48fafb55244f9bf40ebfccea09730682e3a50d2fbc28b52da9ce135c2da3365ae901adc1bd53ef82090334867b7250db54
  auth0_client_secret: 8c5132ccd85bc1ef6725f37912bc7877f3c3381e8571c66c8f2047640c021946
  SMTP_ADDRESS: smtp.gmail.com
  SMTP_DOMAIN: 13.59.121.121
  SMTP_PASSWORD: May061983%&
  SMTP_USERNAME: jbcreativeconceptnyc@gmail.com
test:
  secret_key_base: 4476b9ccebad99a0a9e2767878529ea83c990eabfb2cefefdcb4dfdeb92e2ef0bed9efa05d12592c9cf0e7ad34a7b76816fc2958850683f1a99239a1a9c259b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 46b6271010b5e5b3aeb0babcc4062e99ebe6990f3b5f487bd68c5efe52029cb15d773558f6b41c1538c4fd354b987408d42c366a04355fd7d1ef34e86bfccded
  auth0_client_secret: 8c5132ccd85bc1ef6725f37912bc7877f3c3381e8571c66c8f2047640c021946
  SMTP_ADDRESS: smtp.gmail.com
  SMTP_DOMAIN: 13.59.121.121
  SMTP_PASSWORD: May061983%&
  SMTP_USERNAME: jbcreativeconceptnyc@gmail.com